CREATE USER test WITH PASSWORD 'password';
ALTER USER test WITH SUPERUSER;
CREATE DATABASE application;
CREATE DATABASE user_service;
GRANT ALL PRIVILEGES ON DATABASE application TO test;
GRANT ALL PRIVILEGES ON DATABASE user_service TO test;
