server:
  port: 8765
eureka:
  instance:
    hostname: api-gateway
    #prefer-ip-address: true
  client:
    registerWithEureka: false
    #fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: application
          uri: lb://AVAILABILITY-SERVICE
          predicates:
            - Path=/api/v1/availability/**
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/persons/**, /api/v1/competence/**, /api/v1/competenceporfiles/**