spring:
  cloud:
    gateway:
      routes:
        # Route for Authentication Service
        - id: auth-service
          uri: http://localhost:5000
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=2

        # Route for User Service
        - id: user-service
          uri: http://localhost:5050
          predicates:
            - Path=/api/persons/**
          filters:
            - StripPrefix=2

        # Route for Application Service
        - id: application-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/availability/**
          filters:
            - StripPrefix=2
