server:
  port: 8765
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: application
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/availability/**
        - id: auth-service
          uri: http://localhost:5000
          predicates:
            - Path=/api/v1/auth/**
        - id: user-service
          uri: http://localhost:5050
          predicates:
            - Path=/api/v1/persons/**,