server:
  port: 8090
spring:
  application:
    name: application
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres_sql:5432/application
    username: test
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect