server:
  port: 5050

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service  # for docker use jdbc:postgresql://postgres-sql:5432/user_service
    username: newuser
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  application:
    name: user-service
  sql:
    init:
      mode: always

application:
  security:
    jwt:
      secret-key: cf3e42fb25c974013a0358098d01cc3f31b9ee25a27d6a24df92ab9c87e4081e
      expiration: 60000 # one minute
      refresh-token:
        expiration: 864000000 # 1 day