
server:
  port: 5000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    username: test
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 60000 # one minute
      refresh-token:
        expiration: 864000000 # 1 day
